### ISSUE TITLE
Angular 2 Module

### ISSUE THREAD

**Issue by KevinBeckers** [postcodeapi/postcodeapi#61]
Hallo,

Ik ben momenteel bezig met een angular 2 project. 
Hiervoor heb ik een module gemaakt om met jullie api te communiceren.
Deze wil ik graag met jullie delen. Misschien kan ik iemand hiermee helpen.

[https://github.com/KevinBeckers/NG2-postcodeapi](https://github.com/KevinBeckers/NG2-postcodeapi)

**Comment by dvh** [comment]
Thanks! We lanceren binnenkort een nieuwe website waar ook ruimte komt voor dit soort contributions, dus die nemen we dan gelijk mee!

**Comment by Tommertom** [comment]
Thx @KevinBeckers 

Saved my life!!!

**Comment by DennisVredeveld** [comment]
Sorry, maar ik zou deze implementatie niet gebruiken. Deze vereist namelijk dat gebruikers hun API key in de front-end opslaan en daarmee dus vrijgeven voor gebruikers van hun applicatie.
M.i. zou je API key nooit in de front-end terecht mogen komen. Om calls vanuit de front-end te kunnen doen, kun je beter een widget met token gebruiken (zie https://github.com/postcodeapi/postcodeapi/blob/master/docs/widget.md)
