### ISSUE TITLE
Ik blijf "missing authentication token" terug krijgen

### ISSUE THREAD

**Issue by grindplanet** [postcodeapi/postcodeapi#67]
Ben een redelijke newbie met API. Probeer het voor elkaar te krijgen in FileMaker. Maar ook in PostMan gaat het fout. 
Postman:
url: https://api.postcodeapi.nu/v2/addresses/?postcode=6715GH&number=2
POST
Header key: X-Api-Key
Header value: geheime key
Is er nog iets mis met mijn account? Of zie ik iets heel simpels over het hoofd?

http status: 403 Forbidden

collin@popschool

**Comment by grindplanet** [comment]
http status: 403 Forbidden

**Comment by dvh** [comment]
@grindplanet je moet geen `POST` doen maar een `GET` ;-)

**Comment by grindplanet** [comment]
kuch kuch hahahahaha
werkt meteen ;)
TX!
