### ISSUE TITLE
Cors error

### ISSUE THREAD

**Issue by Coenmathijssen** [postcodeapi/postcodeapi#73]
Ik probeer de API werkende te krijgen in Vue + Nuxt, in combinatie met Axios voor de GET request. Hierbij gebruik ik de volgende code:

`axios.get('https://api.postcodeapi.nu/v3/lookup/${this.postalCode}/${this.houseNumber}', {
            headers: {
              'x-api-key': process.env.POSTAL_KEY,
              'Access-Control-Allow-Origin': '*',
              'Access-Control-Allow-Headers': '*'
            }
          })
          .then((res) => {
          })`
 
Helaas krijg ik hierbij, lokaal en in productie, een CORS error. Namelijk: 'Response to preflight request doesn't pass access control check: It does not have HTTP ok status.' Moet ik nu per se een proxy gebruiken om de API werkende te krijgen? Is er niet een manier op een Access-Control-Allow-Origin header op de API te krijgen vanuit de server van postcodeapi? Om zelf een proxy te bouwen vind ik redelijk veel gedoe en iets als cors-anywhere doe ik liever niet in verband met betrouwbaarheid.

Thanks!

**Comment by dvh** [comment]
De API is inderdaad niet benaderbaar vanuit de client, dan zou je namelijk je API key exposen. Je moet dus inderdaad zelf een proxy bouwen, of je kunt onze [widget](https://github.com/postcodeapi/postcodeapi/blob/master/docs/widget.md) gebruiken.

**Comment by Coenmathijssen** [comment]
Oke helder, thanks voor de snelle reactie. Dan ga ik gebruik maken van de widget van postcodeapi.
